# Generated by Django 4.2.19 on 2025-02-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
